# Generated by Django 4.1.1 on 2022-09-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccimo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sideeffect',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
