# Generated by Django 4.1.1 on 2022-09-15 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccimo', '0003_sideeffect_chills_sideeffect_fatigue_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sideeffect',
            table='sideeffect',
        ),
    ]
