# Generated by Django 4.1.1 on 2022-09-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccimo', '0004_alter_sideeffect_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='questioner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Q0', models.CharField(max_length=100, null=True)),
                ('Q1', models.CharField(max_length=100, null=True)),
                ('Q2', models.CharField(max_length=100, null=True)),
                ('Q3', models.CharField(max_length=100, null=True)),
                ('Q4', models.CharField(max_length=100, null=True)),
                ('Q5', models.CharField(max_length=100, null=True)),
                ('Q6', models.CharField(max_length=100, null=True)),
                ('Q7', models.CharField(max_length=100, null=True)),
                ('Q8', models.CharField(max_length=100, null=True)),
                ('Q9', models.CharField(max_length=100, null=True)),
                ('Q10', models.CharField(max_length=100, null=True)),
                ('Q11', models.CharField(max_length=100, null=True)),
                ('Q12', models.CharField(max_length=100, null=True)),
                ('Q13', models.CharField(max_length=100, null=True)),
                ('Q14', models.CharField(max_length=100, null=True)),
                ('Q15', models.CharField(max_length=100, null=True)),
                ('Q16', models.CharField(max_length=100, null=True)),
                ('Q17', models.CharField(max_length=100, null=True)),
                ('Q18', models.CharField(max_length=100, null=True)),
                ('Q19', models.CharField(max_length=100, null=True)),
                ('Q20', models.CharField(max_length=100, null=True)),
                ('Q21', models.CharField(max_length=100, null=True)),
                ('Q22', models.CharField(max_length=100, null=True)),
                ('allergy', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'questioner',
            },
        ),
    ]
