# Generated by Django 4.1.1 on 2022-09-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccimo', '0005_questioner'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioner',
            name='Q23',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='questioner',
            name='Q24',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
