# Generated by Django 4.1.1 on 2022-09-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccimo', '0006_questioner_q23_questioner_q24'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sideeffect',
            name='chills',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='fatigue',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='fever',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='feverish',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='headache',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='induration',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='itch',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='join_pain',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='muscle_ache',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='nausea',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='redness',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='swelling',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='tenderness',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='vomiting',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='sideeffect',
            name='warmth',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
